/**
 * Ingredient words that betray an allergen, for every feature that filters one.
 *
 * There were two of these — ALLERGEN_KEYWORDS for recipes, ALLERGEN_TERMS for
 * coupons — and they disagreed in eleven of twelve categories while both files
 * described allergens as a hard rule that errs toward dropping. Recipes did not
 * know teriyaki is soy, dijon is mustard, or hummus is sesame; coupons did not
 * know soy sauce is wheat, or that feta and mascarpone are dairy.
 *
 * This is the union, which is the only merge consistent with what both files
 * already said they were for: a false positive costs someone one recipe or one
 * coupon, a false negative costs them an allergic reaction.
 *
 * Keys match the `allergies` options in onboardingQuestions.ts. Matching is
 * substring-based and deliberately over-broad — "butternut squash" trips the
 * dairy rule through "butter", and that is the correct direction to be wrong in.
 *
 * Pure data, no imports, so every runtime and the browser bundle can read it.
 */
export const ALLERGEN_TERMS: Readonly<Record<string, readonly string[]>> = {
  Peanuts: [
    "arachis",
    "groundnut",
    "peanut",
    "satay",
  ],
  "Tree nuts": [
    "almond",
    "brazil nut",
    "cashew",
    "filbert",
    "frangipane",
    "hazelnut",
    "macadamia",
    "marzipan",
    "nougat",
    "nutella",
    "pecan",
    "pine nut",
    "pistachio",
    "praline",
    "walnut",
  ],
  "Milk or dairy": [
    "brie",
    "butter",
    "buttermilk",
    "casein",
    "cheddar",
    "cheese",
    "cream",
    "custard",
    "dairy",
    "feta",
    "gelato",
    "ghee",
    "half and half",
    "mascarpone",
    "milk",
    "mozzarella",
    "parmesan",
    "ricotta",
    "whey",
    "yoghurt",
    "yogurt",
  ],
  Eggs: [
    "aioli",
    "albumen",
    "albumin",
    "custard",
    "egg",
    "frittata",
    "mayo",
    "mayonnaise",
    "meringue",
    "omelet",
    "omelette",
  ],
  "Wheat or gluten": [
    "bagel",
    "barley",
    "biscuit",
    "bread",
    "breadcrumb",
    "cake",
    "cereal",
    "cookie",
    "couscous",
    "cracker",
    "croissant",
    "farro",
    "flour",
    "gluten",
    "noodle",
    "orzo",
    "panko",
    "pasta",
    "pastry",
    "phyllo",
    "pizza",
    "pretzel",
    "puff pastry",
    "rye",
    "seitan",
    "semolina",
    "soy sauce",
    "spelt",
    "tortilla",
    "wheat",
  ],
  Soy: [
    "edamame",
    "miso",
    "soy",
    "soya",
    "tamari",
    "tempeh",
    "teriyaki",
    "tofu",
  ],
  Fish: [
    "anchovies",
    "anchovy",
    "caesar",
    "cod",
    "fish",
    "halibut",
    "herring",
    "mackerel",
    "salmon",
    "sardine",
    "snapper",
    "tilapia",
    "trout",
    "tuna",
    "worcestershire",
  ],
  Shellfish: [
    "calamari",
    "clam",
    "crab",
    "crawfish",
    "crayfish",
    "lobster",
    "mussel",
    "octopus",
    "oyster",
    "prawn",
    "scallop",
    "shellfish",
    "shrimp",
    "squid",
  ],
  Sesame: [
    "benne",
    "halva",
    "hummus",
    "sesame",
    "tahini",
    "za'atar",
    "zaatar",
  ],
  Mustard: [
    "dijon",
    "mustard",
  ],
  Celery: [
    "celeriac",
    "celery",
  ],
  Sulfites: [
    "dried apricot",
    "sulfite",
    "sulphite",
    "wine",
  ],
};
